### PR TITLE
Support for more rabbitpy features.

### PR DESCRIPTION
**Pull request by gabriel10619**
Support for user/pass credentials in rabbitmq-server connection.

Support for 'rabbitpy.message.properties' when using EventPublisher and EventSubscriber. (option dictionary in publish() arguments)

'routing_key_only' argument to 'EventPublisher.publish()'. Useful when communicating between clients that may not be using the same AMPQ library, or if you want to create 
your own format for queue names. This can be further developed to allow for direct queue communication (Through the use of default direct exchange). 

b_rabbit.properties() object that functions similarly to the 'pika.BasicProperties()' object.

---------------------------------------------------------------------------------------------

test_publisher will send a message object with properties.

test_subscriber will check the properties of the received message and confirm it is correct.

### CODE REVIEW

**Comment by gabriel10619** [comment]
The syntax error from commit b5e8351 has been corrected.

One major change here is that the subscriber will pass a full rabbitpy message object to the event listener. Not just the body. This will require changes to the event listeners of anyone using b_rabbit, but will allow for much more information

**Comment by gabriel10619** [comment]
Reopening PR. I closed due to the TRAVIS CI error, but I checked the method in my local environment and the publish method still returns the correct boolean value.

**Comment by gabriel10619** [comment]
```
correlation_id of message is: 10
published bool is: True
```
^
This is a portion of the output of the following test code:

```
def publish(self, message, properties):
                published = self.publisher.publish(routing_key=self.out_queue, payload=message, properties=properties)
                print("published bool is: " + str(published))
```

The properties are working, and published = True. The correlation id is printed from the event handler of the consumer, so I know the properties are maintained after publishing. Any idea why the Travis ci test would return a failure like that?

(assert published(None) == True)?

**Comment by nidhaloff** [comment]
@gabriel10619 It looks good to me, thanks. However, the test for the publisher keeps failing in travis. Do you have any idea why? did you checked the tests locally or in travis?

**Comment by gabriel10619** [comment]
@nidhaloff i am not sure why it is failing Travis. When I saw the error I went and tested it in my local environment and it worked fine. (Ex:   my sample code in the above comment). It is especially strange because it passes the consumer test! (It receives a message, and in the code the published = publisher.publish).

I'll have a look at it in a moment and see if I can't make a PR that passes Travis ci test.

**Comment by gabriel10619** [comment]
@nidhaloff Sorry it took so long to fix things up, but everything should be good to go now! Just one warning from Travis ci but I believe that warning was flagged even before my build. Thanks for your patience :) If there is any extra documentation you would like, let me know here or shoot me an email and I would be happy to contribute again or provide a write-up of the changes.

**Comment by nidhaloff** [comment]
@gabriel10619 thanks for your work. Can you describe what the problem was?

**Comment by gabriel10619** [comment]
@nidhaloff To be honest, I am not sure! It was either a syntax error in my call to channel.enable_publisher_confirms, or an issue with the way I close the channel directly after publishing. I chose to do this because RabbitMQ suggests against opening many channels, and instead to reuse channels. I see that your code currently creates a new channel from the BRabbit connection for every publish, so I have left it like this for now, but I plan on doing some more testing on this so we can work around that, and possibly reuse a main channel (I do not know how this will affect multithreading yet, I know it can be very picky in these AMPQ libraries).

**Comment by nidhaloff** [comment]
@gabriel10619 Notice that I'm use context managers (the with ... syntax). Here is an example

 `with self.b_rabbit.connection.channel() as channel:`

If you use the with syntax, than the channel will be closed at the end automatically without needing to call close ;)

**Comment by gabriel10619** [comment]
@nidhaloff Ah! I was not aware that this automatically closed the channel as well. Thank you for the info.

**Comment by nidhaloff** [comment]
@gabriel10619 Context managers are a very powerful concept. 
You can read about it here https://book.pythontips.com/en/latest/context_managers.html

**Pull request merged**
