### PR TITLE
correct fix for logging

### PR DESCRIPTION
**Pull request by PhMakowski**
Please accept this full fix for the logging issue and push it to pypi (new version 1.2.4)
Thanks

### CODE REVIEW

**Comment by PhMakowski** [comment]
Thanks, can you please publish this version on PyPi ?

**Comment by nidhaloff** [comment]
Done. Thanks for the PR

**Comment by PhMakowski** [comment]
> Done. Thanks for the PR

hum, for me PyPi is still in 1.2.3 Released: Jul 22, 2021

**Comment by nidhaloff** [comment]
maybe it will take a second to show up

**Pull request merged**
